app:
  host: http://localhost:8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  profiles: local

---
spring:
  profiles: dev

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: connectuser
    password: connect123!@#

  mail:
    host: smtp.gmail.com
    port: 587
    # 내 구글 계정
    username: vfrvfr4207@gmail.com
    # 발급받은 App 패스워드
    password: addfznoawwltxlue
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
